CREATE TABLE user_roles(
    user_role_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE RESTRICT ON UPDATE CASCADE ,
    CONSTRAINT UQ_user_roles_user_id UNIQUE (user_id),
    PRIMARY KEY (user_role_id)
);
