CREATE TABLE events(
    event_id    BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type        VARCHAR(50) NOT NULL
        CHECK ( type IN ('LOGIN_ATTEMPT',
                         'LOGIN_ATTEMPT_FAILURE',
                         'LOGIN_ATTEMPT_SUCCESS',
                         'PROFILE_UPDATE',
                         'PROFILE_PICTURE_UPDATE',
                         'ROLE_UPDATE',
                         'ACCOUNT_SETTINGS_UPDATE',
                         'PASSWORD_UPDATE',
                         'MFA_UPDATE')
            ),
    description VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_events_type UNIQUE (type),
    PRIMARY KEY (event_id)
);
