CREATE TABLE user_events(
    user_event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    device        VARCHAR(100) DEFAULT NULL,
    ip_address    VARCHAR(100) DEFAULT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id       BIGINT NOT NULL,
    event_id      BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (event_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY (user_event_id)
);
