CREATE TABLE account_verifications(
    account_verification_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id                 BIGINT NOT NULL,
    url                     VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_account_verifications_user_id UNIQUE (user_id),
    CONSTRAINT UQ_account_verifications_url UNIQUE (url),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (account_verification_id)
);
