CREATE TABLE reset_password_verifications(
    reset_password_verification_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    url                            VARCHAR(255) NOT NULL,
    user_id                        BIGINT NOT NULL,
    expiration_date                TIMESTAMP NOT NULL,
    CONSTRAINT UQ_reset_password_verifications_url UNIQUE (url),
    CONSTRAINT UQ_reset_password_verifications_user_id UNIQUE (user_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (reset_password_verification_id)
);
