CREATE TABLE two_factor_verifications(
    two_factor_verification_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id                    BIGINT NOT NULL,
    code                       VARCHAR(10) NOT NULL,
    expiration_date            TIMESTAMP NOT NULL,
    CONSTRAINT UQ_two_factor_verifications_user_id UNIQUE (user_id),
    CONSTRAINT UQ_two_factor_verifications_code UNIQUE (code),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (two_factor_verification_id)
);
